### ISSUE TITLE
Display data tooltip when selecting graph data

### ISSUE THREAD

**Issue by JeremyMain** [JeremyMain/GPUProfiler#10]
Looking at graphs is interesting but when you need to know the actual values clicking on the line data will display a tooltip with the utilization and value (where supported).

**Comment by JeremyMain** [comment]
Experimented with various ways to display the data. 
This looks the most reasonable.
![image](https://cloud.githubusercontent.com/assets/19617537/21234233/3ff2f330-c335-11e6-9533-c14fa3acb2a8.png)

**Comment by diebel** [comment]
I like it

Milan

**Comment by JeremyMain** [comment]
adding a hot key to toggle between utilization percentages and actual values for system memory and frame buffer

**Comment by JeremyMain** [comment]
For prior beta users the display function has been updated to eliminate the font-buffer drawing flicker via MemDC
