### ISSUE TITLE
Quatro K620 not showing up

### ISSUE THREAD

**Issue by dtitco69** [JeremyMain/GPUProfiler#100]
we have just attempted to check the GPU usage on a K620 card and were unable to see the GPU in the software

**Comment by JeremyMain** [comment]
Can you provide a screenshot of GPUProfiler and/or save and share the resulting GPD file?
What version of the NVIDIA driver are you using?

**Comment by dtitco69** [comment]
hi Jeremy, it looks like it was an issue with an older driver we were using 340.84 as its on the compatibility list for the software we use however I cloned the drive and ran it again on updated drivers with no issues

**Comment by dtitco69** [comment]
![k620](https://user-images.githubusercontent.com/29754525/43136653-57098384-8f41-11e8-89da-ba7871866746.png)

**Comment by JeremyMain** [comment]
Since this appears to be resolved, I will close this issue.
