### ISSUE TITLE
No GPU % shown

### ISSUE THREAD

**Issue by jmauser** [JeremyMain/GPUProfiler#109]
Hi,
When I run the gpu profiler on a vm running a nvidia k1 with 2GB FB.   I see no gpu% information.  I can not find info in the project if this k1 card just is not cable of having this info shown or if it's a bug.  I attached a screen shot showing a solidworks job running that *should* be using gpu from the Solidworks benchmark utility. 
![gpu_profiler_no_gpu](https://user-images.githubusercontent.com/19393900/52812167-e0546180-3064-11e9-8c07-7267702a3b1b.PNG)

**Comment by JeremyMain** [comment]
@jmauser 
The GPU utilization metrics for GRID K1 and K2 cards are not supported by the NVML API, this is the reason why the utilization is not displayed.
For this generation card, the best alternative method would be to use a VM with GPU passthrough as that supports all the GPU metrics.
