### ISSUE TITLE
Specified sample interval isn't apply as default

### ISSUE THREAD

**Issue by kwowdai** [JeremyMain/GPUProfiler#145]
I put a check mark on "Save current setting as default"  from Options.
However, once GPU Profiler tool was restarted, the parameter I specified wasn't set on Sample interval as default and automatically returned to original "1" second.

**Comment by JeremyMain** [comment]
I will reproduce this issue (and fix it)

**Comment by JeremyMain** [comment]
Found and fixed the issue, will be in the next minor release

**Comment by JeremyMain** [comment]
Complete and closing with release v1.07a3
