### ISSUE TITLE
How to build on linux ?

### ISSUE THREAD

**Issue by WilliamWangPeng** [JeremyMain/GPUProfiler#147]
Hello dear author,  
    Honor to write a letter to you, I wonder how to build GPUProfiler on ubuntu18.04?  

thank you  
best regards  
William

**Comment by JeremyMain** [comment]
William, I have a beta version of GPUProfiler for Linux that collects the base information and outputs to a .GPD formatted file for analysis in the Windows version of GPUProfiler. 
NOTE: It does not include support for remoting protocol metrics at this time.

**Comment by JeremyMain** [comment]
GPUProfiler for Linux project is available. Closing this issue
https://github.com/JeremyMain/GPUProfiler-for-Linux
