### ISSUE TITLE
Removing "Host" (computername) from header of the * .GPD file

### ISSUE THREAD

**Issue by Joerg-Zimmermann** [JeremyMain/GPUProfiler#148]
Hello JeremyMain, is it possible to remove the host (computername) from header (first line in file) of the * .GPD file by activating a (new) option? I would like to make the analysis with the GPUProfiler completely anonymous. This is necessary because of data protection in Europe.
Thank you for your answer in advance. 
Best regards
Joerg

**Comment by Joerg-Zimmermann** [comment]
Or is there a chance to the the output file direct in CSV format? Because in the CSV export there is no "Host" entry.
Or ist there a possebility to covert all GPD files form a folder automatically with a batch program in CSV files?
Thanks for your answer.
Best regards
Joerg

**Comment by JeremyMain** [comment]
My apologizes not seeing your request sooner @Joerg-Zimmermann 

I could make a new preference to not record the host name in the GPD file, this would need to be added to the current release as I am closing in on the next release with more metrics...that requires even more validation before release.

Batch conversion of GPD files to CSV has been requested several times. Let me see how long it will take to create a GPD2CSV tool.
I would like to not output to CSV directly as the data and environment relationship becomes disconnected. Having the system configuration information with the utilization data is a key reason why I made the tool.

**Comment by Joerg-Zimmermann** [comment]
Hello JeremyMain,
many thanks for your response. No problem that it took a while. Your program is excellent, thank you for making it available.
It would be great if you could implement the extension (new preference to remove the computername) quickly.
You are right, with the direct output of the logs as CSV file the reference to the hardware configuration is lost.
In my case, however, I found this to be an advantage for data protection. I have to analyze many computers that all have identical hardware.
Thank you for your help in advance.
Best wishes
Jörg

**Comment by JeremyMain** [comment]
@Joerg-Zimmermann 
I have a test version of gpd2csv for you to test, can you send me an email [ jmain @ gpuprofiler.com ] so I can share it with you?
I will look at adding the new preference to not capture/record the hostname next.

**Comment by JeremyMain** [comment]
@Joerg-Zimmermann 
Do you have a large number of existing GPD files to remove the hostname information from?
I could make another command line tool to remove the hostname data from existing GPD files similar to the function of gpd2csv.

**Comment by JeremyMain** [comment]
Implemented a new option to remove the system identifier (hostname) from the base system data collection routine.
This preference state is saved with the rest of the application preferences. When running from the command line I will need to add an additional option to specify not to collect that information. I don't expect anyone that is running from the command line to set the application preferences on every system that is collecting data from.

![image](https://user-images.githubusercontent.com/19617537/123551191-ae627680-d7ab-11eb-8096-adb9fa89111f.png)

**Comment by JeremyMain** [comment]
New command line flag "-p" added to not collect system identifier data (hostname)
![image](https://user-images.githubusercontent.com/19617537/123551661-c3d8a000-d7ad-11eb-9114-ee1efc273d08.png)

**Comment by JeremyMain** [comment]
Tested new command line option to confirm that the default option in the dialog does not override the command line flag.
Will close issue once v1.07a3 is released.

**Comment by JeremyMain** [comment]
Complete and closing with release v1.07a3

**Comment by Joerg-Zimmermann** [comment]
Hello JeremyMain,
many, many thanks for your solution in your new GPUProfiler version to remove the hostname. That's great! 
Also many thanks for the additional tool to convert the *.GPD files into *.CSV files. It's very helpful.
Best regards
Jörg
