### ISSUE TITLE
Create a GPD2CSV batch converter for .GPD files into .CSV files

### ISSUE THREAD

**Issue by JeremyMain** [JeremyMain/GPUProfiler#149]
convert single / multiple .GPD file(s) to .CSV format
wildcard support
convert all GPD files in a directory
concatenate all GPD files into a single CSV file as an option?

**Comment by JeremyMain** [comment]
in progress

**Comment by JeremyMain** [comment]
![image](https://user-images.githubusercontent.com/19617537/123200385-91981b80-d4eb-11eb-8b11-5c15e4e8e305.png)

First beta release of the tool tested and shared with requester.

**Comment by JeremyMain** [comment]
Complete and closing with release v1.07a3

**Comment by Outtie9** [comment]
Hey Jeremy - I am wondering if this post is related to something I'm working on. Trying to convert a .gpd file that was exported from Cyrious SMS software into a .csv coherently so I can import it to QBO. My skills in this area are severely lacking.
