### ISSUE TITLE
.NET applications not shown in Process list

### ISSUE THREAD

**Issue by mickhuska** [JeremyMain/GPUProfiler#163]
Hi Jeremy, we're trying to monitor vGPU utilization for a custom .NET app on Windows Server 2022 VM with Citrix LTSR 2203. We believe that app is being rolled into the TOTAL, but not broken out individually like other apps. We checked the process permissions, which seem to be as open as possible. Do you have any suggestions as to why custom C# .exe applications may not show up in the process list?

**Comment by JeremyMain** [comment]
@mickhuska,
Let me check the current process detection behavior of a C# application that uses GPU resources.

**Comment by JeremyMain** [comment]
@mickhuska I downloaded and built the samples from [SharpGL](https://github.com/dwmkerr/sharpgl) and the process appeared in the utilization list within GPUProfiler.

![image](https://user-images.githubusercontent.com/19617537/205487468-b0a0d14d-7719-4295-a5f4-32362e67985e.png)

**Comment by JeremyMain** [comment]
Closing this issue since the .NET application processes are shown.
@mickhuska if you still have this issue please open a new bug with more details about your application.
GPUProfiler uses the NVIDIA API NVML and process details are collected from that API.
