### ISSUE TITLE
Hide histograms of resources that have no data, not supported or 0 values only

### ISSUE THREAD

**Issue by JeremyMain** [JeremyMain/GPUProfiler#18]
Hide Analysis histograms where no data is available.

![image](https://cloud.githubusercontent.com/assets/19617537/21483091/5c5dd434-cbc0-11e6-8be4-e0d1a09fe5a8.png)

In this example both have no non-zero utilization data and should not be displayed until data exists. This applies for all resource utilization data.

**Comment by JeremyMain** [comment]
This will free up some display space for histograms that actually have data.

**Comment by diebel** [comment]
These plots have data in them, the first bucket is from 0-10%

Milan

**Comment by JeremyMain** [comment]
Yes, they have data but the data is collected as '0' where not supported.
Currently I am not planning on implementing the auto-hiding of totally zero data, but the hiding of the histogram when the plot data is deselected. The same for the roll-over utilization data.
![image](https://cloud.githubusercontent.com/assets/19617537/21484316/d718ca40-cbd3-11e6-8b31-f879e4541dac.png)

**Comment by diebel** [comment]
There are two bins, 0 and (0-10]. The brackets state whether the boundary is part of the bin.

The complete bin list is:

0
(0-10]
(10-20]
...
(90-100]

The left boundary is not part of the interval.

Milan
