### ISSUE TITLE
Add "monitor" mode

### ISSUE THREAD

**Issue by JeremyMain** [JeremyMain/GPUProfiler#32]
When the tool is being used to simply monitor for demo purposes or for performing an initial investigation where the entire sample term data is not intended to being saved, the mode would allow endless monitoring of the resource states. 
When the monitor mode is stopped, an option to save the data would be possible within the current visible range.

**Comment by JeremyMain** [comment]
This may not make it into v1.0.5 due to time constraints...

**Comment by mdemoret** [comment]
I assume this got bumped from 1.05? 

Very interested in this behavior so I can just leave the profiler running in the background while developing an application and see a rolling window of utilization without having to restart frequently.

**Comment by JeremyMain** [comment]
![image](https://user-images.githubusercontent.com/19617537/31230519-427bdbe0-aa1f-11e7-9340-3587c48f8c89.png)

Nothing like a flight to allow one to focus.

Don't batch refresh the releases just yet, some more testing needs to be done.

**Comment by mdemoret** [comment]
Great! Looks good. I assume that it just starts over at the beginning once it reaches the end of the graph? Or does it function more like a sliding window?

I keep checking for updates. Very excited about this feature.

**Comment by JeremyMain** [comment]
I am debating how to best show the roll-over, and represent the timescale.
I think the sliding window would look best.
Another feature is that the data can be saved. 
Example, when you observe something in the monitor view and then stop monitoring, you can save that portion of the monitor data. 
Currently, starting the monitor again will clear the previous data.

**Comment by mdemoret** [comment]
For what it's worth, I think the sliding view works best but if it's easier to implement a rolling window, that works too. And the ability to save the most recent data at any given time would be a great feature.

Btw, if you would like help with some of the coding work, shoot me an email to my @nvidia.com email address (Should be able to search for me on the company directory). I would be happy to help and I have pretty extensive background in GUI development in C++, C#, and various web frameworks.

**Comment by JeremyMain** [comment]
Completed and to be in the v1.06 release. 
Had to merge the "workin on it" branch with a separate bugfix branch.
