### ISSUE TITLE
GPUProfiler_1.04-x64 Crashes on W7x64 with Quadro K2200 (353.82)

### ISSUE THREAD

**Issue by BeerMacht** [JeremyMain/GPUProfiler#34]
GPUProfiler Version: GPUProfiler_1.04-x64

Type: Physical
OS: W7x64 Professional SP1 / German UI
CPU: Intel Xenon E31281v3 @3.70 GHz
RAM: 16 GB

How can we provide more Information to you?
What do you need?

Best Regards

**Comment by JeremyMain** [comment]
Thanks for the bug report!
You have provided all of the info required for me to replicate the environment, thank you!

When does the application crash, on launch or at a certain point during operation?

You can send additional info via email if required to jmain@gpuprofiler.com but general bug discussion is best here on GitHub.

**Comment by JeremyMain** [comment]
Actual version appears to be 1.02, waiting for confirmation that using 1.04 the issue is not observed.

**Comment by JeremyMain** [comment]
If there is no update I am going to close this issue

**Comment by JeremyMain** [comment]
Closing issue
