### ISSUE TITLE
Request of 32 bit version to be run on macOS under Wine

### ISSUE THREAD

**Issue by borshpro** [JeremyMain/GPUProfiler#51]
Current 64-bit release couldn't be run under [Wine](https://www.winehq.org/) (to see logs saved from Windows).

Binary distribution request:
- Please, compile 32-bit Windows executable.

Thank you in advance.

**Comment by JeremyMain** [comment]
The NVIDIA API that is being used for collecting GPU utilization does not support x86 therefore I have not continued supporting x86 builds of the tool.

If a x86 version was to be created it would only have the ability to view previously captured GPD results. Does that meet your requirements?

I have run GPUProfiler under Wine on MacOS as well and did not have any issues. The version was  not the latest x64 version so I would need to reconfirm.

**Comment by JeremyMain** [comment]
I should be noted that when using GPUProfiler on Wine, it was with the intent to only view existing data and not attempt to collect profile data. I just wanted to set the right expectations around support for running GPUProfiler on Wine

**Comment by borshpro** [comment]
I downloaded [GPUProfiler v1.01](https://github.com/JeremyMain/GPUProfiler/releases/download/v1.01/GPUProfiler_v1.01-x86.zip) and after installing VC 2010 runtime, it works on Wine.

**Comment by JeremyMain** [comment]
Next version v1.0.5 will potentially have x86 support since the NVML SDK will support both x86 and x64 again.

Closing
