### ISSUE TITLE
Switching from dark to light mode breaks time/interval setting

### ISSUE THREAD

**Issue by NAUbackup** [JeremyMain/GPUProfiler#59]
Changing on the fly from dark to light mode makes it impossible to edit the time interval and duration settings, even if the process is stopped. I had to exit and re-launch the application.

**Comment by JeremyMain** [comment]
Thanks for reporting this issue.
During profiling the interval and duration can not be changed. After manually stopping or the duration has expired clicking the 'new' button will clear the old profile data and enable the interval and duration to be changed. 
The behavior is the same for cases where the GPD file is being loaded, until 'new' is selected the interval and duration are not editable.
