### ISSUE TITLE
Automatic timed series profiling works only on first loop ?

### ISSUE THREAD

**Issue by jpsirera** [JeremyMain/GPUProfiler#72]
Using version 1.05.

Trying to record VDI session GPU usage, launching gpuprofiler at session Startup via command line : 

**GPUProfiler.exe -m -i 1 -d 10 -r144 -f \\\UNCPath\\%username%-profile.gpd -t -x**

As GPD file is written on disk at the end of the loop, we've used 10 minutes loops repeated 144 times = 1 day.

First GPD file is well generated, but not the other ones.

If looking at GPUProfiler GUI, tool succesfully goes to "Run 2 of 144...", but seems to be stuck at the end of the second loop.

Am I misusing the tool ? Bug ?

Thanks for your help !

**Comment by JeremyMain** [comment]
jpsirera,
Thank you for reporting this issue. 
I was able to reproduce the behavior and will look into the cause. 
Stay tuned.

**Comment by jpsirera** [comment]
Thank you Jeremy.
If technically possible, if would be nice if .gpd file would be written continuously during tool's runtime instead at the end of each loop.

In my use case, I would like to launch the tool silently at user's session logon and record whole session, and be sure to have data, no matter when user decides to logoff (ie : before the first loop duration !)

Regards

**Comment by JeremyMain** [comment]
I have looked into the failure and working on a fix for 1.05a. That release will also include some of the other minor fixes for v1.05. I don't have a specific release date yet but I hope within a few days.

Immediate GPD write
I would need to add an additional command option to implement the immediate write of the data to the GPD file and add more logic to the serialization functions.

**Comment by JeremyMain** [comment]
Completed in v1.05a release

**Comment by jpsirera** [comment]
Thanks Jeremy, works like a charm now 👍

**Comment by JeremyMain** [comment]
Glad to hear that. I modified the sample period down to a few miliseconds to accelerate the testing and exercise this. 
As far as can I write the content to the file continuously or every minute, I will need to add that as a new issue. Writing / updating the file every minute would be an easier task to complete and would provide a better result than what you are currently experiencing.
